---
http_interactions:
- request:
    method: put
    uri: http://192.168.50.2:4440/api/12/project/nonexistent/config
    body:
      encoding: UTF-8
      string: '{"resources.source.1.type": "file"}'
    headers:
      Content-Type:
      - application/json
      X-Rundeck-Auth-Token:
      - OPIfQ6MOnevhlFThG1af4GAcbPdAgh0B
      Accept:
      - application/xml
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Set-Cookie:
      - JSESSIONID=2hvga0j6fvgvu4w67fbw44p8;Path=/
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Content-Type:
      - text/xml;charset=UTF-8
      X-Rundeck-Api-Version:
      - '12'
      Transfer-Encoding:
      - chunked
      Server:
      - Jetty(7.6.0.v20120127)
    body:
      encoding: UTF-8
      string: |-
        <result error='true' apiversion='12'>
          <error code='api.error.item.doesnotexist'>
            <message>Project does not exist: nonexistent</message>
          </error>
        </result>
    http_version: 
  recorded_at: Sat, 07 May 2016 10:31:34 GMT
recorded_with: VCR 3.0.1
