---
http_interactions:
- request:
    method: put
    uri: http://192.168.50.2:4440/api/12/project/anvils/config
    body:
      encoding: UTF-8
      string: '{"resources.source.1.type": "file"}'
    headers:
      Content-Type:
      - application/json
      X-Rundeck-Auth-Token:
      - OPIfQ6MOnevhlFThG1af4GAcbPdAgh0B
      Accept:
      - application/xml
  response:
    status:
      code: 200
      message: OK
    headers:
      Set-Cookie:
      - JSESSIONID=19xvsjtxrziiz1dwg27jersfij;Path=/
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      X-Rundeck-Api-Xml-Response-Wrapper:
      - 'false'
      Content-Type:
      - application/xml;charset=UTF-8
      X-Rundeck-Api-Version:
      - '12'
      Transfer-Encoding:
      - chunked
      Server:
      - Jetty(7.6.0.v20120127)
    body:
      encoding: UTF-8
      string: |-
        <config>
          <property key='project.name' value='anvils' />
          <property key='resources.source.1.type' value='file' />
        </config>
    http_version: 
  recorded_at: Mon, 09 May 2016 17:10:40 GMT
recorded_with: VCR 3.0.1
